# Generated by Django 6.0.3 on 2026-03-27 00:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceLevelTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_level_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Niveles Generados')),
                ('area', models.CharField(max_length=255, verbose_name='Área')),
                ('level_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título de Niveles')),
                ('level_description', models.TextField(blank=True, null=True, verbose_name='Descripción de Niveles')),
                ('grade', models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('6', 'Sexto'), ('7', 'Séptimo'), ('8', 'Octavo'), ('9', 'Noveno'), ('10', 'Décimo'), ('11', 'Once')], max_length=2, verbose_name='Grado')),
                ('subject', models.CharField(choices=[('Español / Castellano', 'Español / Castellano'), ('Matemáticas', 'Matemáticas'), ('Ingles', 'Ingles'), ('Sociales', 'Sociales'), ('Ciencias Naturales', 'Ciencias Naturales'), ('Educación Física', 'Educación Física'), ('Filosofía', 'Filosofía'), ('Artística', 'Artística'), ('Ética y Valores', 'Ética y Valores'), ('Informática', 'Informática')], max_length=255, verbose_name='Asignatura')),
                ('competency', models.CharField(max_length=255, verbose_name='Competencia')),
                ('statement', models.TextField(verbose_name='Afirmación')),
                ('learning_evidence', models.TextField(verbose_name='Evidencia de Aprendizaje')),
                ('academic_period', models.CharField(max_length=100, verbose_name='Periodo Académico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_levels', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Docente')),
            ],
            options={
                'verbose_name': 'Nivel de Desempeño',
                'verbose_name_plural': 'Niveles de Desempeño',
                'db_table': 'performance_levels',
            },
        ),
    ]
