# Generated by Django 6.0.3 on 2026-03-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceleveltemplate',
            name='academic_period',
            field=models.CharField(choices=[('Primer periodo', 'Primer periodo'), ('Segundo periodo', 'Segundo periodo'), ('Tercer periodo', 'Tercer periodo')], max_length=20, verbose_name='Periodo Académico'),
        ),
    ]
