# Generated by Django 6.0.3 on 2026-03-27 22:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_alter_performanceleveltemplate_academic_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedLevels',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Niveles Generados')),
                ('low_level', models.TextField(verbose_name='Nivel Bajo')),
                ('basic_level', models.TextField(verbose_name='Nivel Básico')),
                ('high_level', models.TextField(verbose_name='Nivel Alto')),
                ('superior_level', models.TextField(verbose_name='Nivel Superior')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('performance_template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_levels', to='levels.performanceleveltemplate', verbose_name='Plantilla de Desempeño')),
            ],
            options={
                'verbose_name': 'Nivel Generado',
                'verbose_name_plural': 'Niveles Generados',
                'db_table': 'generated_levels',
            },
        ),
    ]
