# Generated by Django 6.0.3 on 2026-03-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0003_generatedlevels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceleveltemplate',
            name='area',
            field=models.CharField(
                choices=[
                    ('Español / Castellano', 'Español / Castellano'),
                    ('Matemáticas', 'Matemáticas'),
                    ('Ingles', 'Ingles'),
                    ('Sociales', 'Sociales'),
                    ('Ciencias Naturales', 'Ciencias Naturales'),
                    ('Educación Física', 'Educación Física'),
                    ('Filosofía', 'Filosofía'),
                    ('Artística', 'Artística'),
                    ('Ética y Valores', 'Ética y Valores'),
                    ('Informática', 'Informática'),
                ],
                max_length=255,
                verbose_name='Área',
            ),
        ),
    ]
