# Generated by Django 6.0.3 on 2026-03-29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("levels", "0004_alter_performanceleveltemplate_area"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentRubric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID de la rúbrica de evaluación",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Título de la rúbrica"),
                ),
                (
                    "rubric_description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Descripción de la rúbrica",
                    ),
                ),
                (
                    "rubric_content",
                    models.TextField(verbose_name="Contenido de la rúbrica"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Fecha de actualización",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de eliminación",
                    ),
                ),
                (
                    "generated_levels",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_rubric",
                        to="levels.generatedlevels",
                        verbose_name="Niveles generados",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rúbrica de evaluación",
                "verbose_name_plural": "Rúbricas de evaluación",
                "db_table": "assessment_rubrics",
            },
        ),
    ]
