# Generated by Django 6.0.3 on 2026-04-04 21:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0006_remove_performanceleveltemplate_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPlanning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255, verbose_name='Tema')),
                ('subtopic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtema')),
                ('class_objective', models.TextField(verbose_name='Objetivo de la Clase')),
                ('duration_minutes', models.IntegerField(verbose_name='Duración (minutos)')),
                ('prompt', models.TextField(verbose_name='Prompt del Docente')),
                ('methodology', models.CharField(blank=True, max_length=255, null=True, verbose_name='Metodología')),
                ('resources', models.TextField(blank=True, null=True, verbose_name='Recursos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('assessment_rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_plannings', to='levels.assessmentrubric', verbose_name='Rúbrica de Evaluación')),
                ('generated_levels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_plannings', to='levels.generatedlevels', verbose_name='Niveles Generados')),
                ('performance_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_plannings', to='levels.performanceleveltemplate', verbose_name='Plantilla de Desempeño')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_plannings', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Docente')),
            ],
            options={
                'verbose_name': 'Planeación de Clase',
                'verbose_name_plural': 'Planeaciones de Clase',
                'db_table': 'class_plannings',
            },
        ),
        migrations.CreateModel(
            name='GeneratedClassPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_content', models.TextField(verbose_name='Contenido Generado')),
                ('ai_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo de IA')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('class_planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_classes', to='levels.classplanning', verbose_name='Planeación de Clase')),
            ],
            options={
                'verbose_name': 'Clase Generada',
                'verbose_name_plural': 'Clases Generadas',
                'db_table': 'generated_class_plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
