# Generated by Django 6.0.3 on 2026-04-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0007_classplanning_generatedclassplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedclassplan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='generatedclassplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
    ]
