# Generated by Django 6.0.3 on 2026-04-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("levels", "0008_generatedclassplan_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performanceleveltemplate",
            name="competency",
            field=models.TextField(verbose_name="Competencia"),
        ),
        migrations.AddField(
            model_name="performanceleveltemplate",
            name="learning",
            field=models.TextField(default="", verbose_name="Aprendizaje"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="performanceleveltemplate",
            name="evaluation_criteria",
            field=models.TextField(default="", verbose_name="Criterios de Evaluación"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="performanceleveltemplate",
            name="assessment_instrument",
            field=models.TextField(default="", verbose_name="Instrumento de Evaluación"),
            preserve_default=False,
        ),
    ]
