# Generated by Django 6.0.3 on 2026-04-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("levels", "0009_performanceleveltemplate_new_pedagogical_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="performanceleveltemplate",
            name="competency",
        ),
        migrations.RemoveField(
            model_name="performanceleveltemplate",
            name="statement",
        ),
        migrations.AddField(
            model_name="performanceleveltemplate",
            name="didactic_resources",
            field=models.TextField(blank=True, default="", verbose_name="Recursos Didácticos"),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="performanceleveltemplate",
            name="learning_evidence",
            field=models.TextField(verbose_name="Evidencias de Aprendizaje"),
        ),
    ]
