# Generated by Django 6.0.3 on 2026-04-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0010_update_template_fields_remove_competency_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceleveltemplate',
            name='didactic_resources',
            field=models.TextField(blank=True, help_text='Puede incluir como guía: recursos didácticos, materiales y actividades pedagógicas', verbose_name='Recursos Didácticos'),
        ),
    ]
