# Generated by Django 6.0.3 on 2026-09-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0011_alter_performanceleveltemplate_didactic_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classplanning',
            name='methodology',
            field=models.TextField(blank=True, null=True, verbose_name='Metodología'),
        ),
    ]
