# Generated by Django 6.0.3 on 2026-04-14 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('levels', '0009_performanceleveltemplate_new_pedagogical_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedClassComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Contenido del comentario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_class_comments', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('generated_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='levels.generatedclassplan', verbose_name='Clase generada')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='interactions.generatedclasscomment', verbose_name='Comentario padre')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'generated_class_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedClassLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('generated_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='levels.generatedclassplan', verbose_name='Clase generada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_class_likes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Me gusta',
                'verbose_name_plural': 'Me gusta',
                'db_table': 'generated_class_likes',
                'constraints': [models.UniqueConstraint(fields=('generated_class', 'user'), name='unique_like_per_user_per_class')],
            },
        ),
    ]
